ModelAgencyIdentity/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ModelAgencyIdentity.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ModelAgencyIdentity/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModelAgencyIdentity.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ModelAgencyIdentity/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModelAgencyIdentity.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ModelAgencyIdentity/Pages/UserApprovals.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ModelAgencyIdentity.Data;
using ModelAgencyIdentity.Data.Entities;

namespace ModelAgencyIdentity.Pages
{
    [Authorize(Policy = "PageOwner")]
    public class UserApprovalsModel : PageModel
    {
        private readonly ApplicationDbContext dbContext;

        public UserApprovalsModel(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public List<ApplicationUser> Users { get; set; }

        public void OnGet()
        {
            Users = dbContext.Users.Where(user => user.AccountState == AccountState.Pending).ToList();
        }

        public IActionResult OnPostApprove(string email)
        {
            var user = dbContext.Users.First(user => user.Email == email);
            if (user != null)
            {
                user.AccountState = AccountState.Approved;
                dbContext.SaveChanges();
            }

            return LocalRedirect("/UserApprovals");
        }

        public IActionResult OnPostReject(string email)
        {
            var user = dbContext.Users.First(user => user.Email == email);
            if (user != null)
            {
                user.AccountState = AccountState.Rejected;
                dbContext.SaveChanges();
            }

            return LocalRedirect("/UserApprovals");
        }
    }
}

ModelAgencyIdentity/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ModelAgencyIdentity/Pages/UserApprovals.cshtml
@page
@model UserApprovalsModel
@{
    ViewData["Title"] = "Approvals";
}

<h2>Approve pending users</h2>
<table>
    @foreach (var user in Model.Users)
    {
        <tr>
            <td>@user.Email </td>
            &nbsp;
            <td>
                <form asp-page-handler="Approve" method="post">
                    <input type="hidden" name="email" value="@user.Email" />
                    <button>Approve</button>
                    &nbsp;~&nbsp;
                </form>
            </td>
            <td>
                <form asp-page-handler="Reject" method="post">
                    <input type="hidden" name="email" value="@user.Email" />
                    <button>Reject</button>
                    &nbsp;~&nbsp;
                </form>
            </td>
            <td>
                <form asp-page="/Details" asp-route-id="@user.Email">
                    <button>Details</button>
                    &nbsp;~&nbsp;
                </form>
            </td>
        </tr>
    }
</table>